### ISSUE TITLE
Integration der StuRa-Infos etc.

### ISSUE THREAD

**Issue by Nos-** [HTWDD/HTWDresden#1]
Hallo, ich hatte schon in der Vorgänger-App einen entsprechenden Issue angelegt. Hier nun der Link dazu.

https://github.com/HTWDD/HTWDD/issues/28

Für Fragen stehe ich natürlich gern zur Verfügung.

**Comment by FestPlatin** [comment]
Ich würde das Thema bevorzugt hier weiter behandeln, da der Fokus zurzeit auf der "neuen" App liegt.

> * Link auf Homepage, Wiki etc.

Für den Stura hatte ich schon eine Kachel unter Verwaltung angedacht. Die Links sollten sich da auch ohne Probleme unterbringen lassen.

> * Kalender (sofern vorhanden und exportierbar)
> * Link auf Homepage, Wiki etc.

Lassen sich beide als RSS-Feed einbinden, auch wenn das nicht gerade die schönste Art ist. Wie hast du dir hier die Einbindung speziell vorstellt? Auf einen extra Eintrag im Menü würde ich gerne Verzichten, da es relativ übersichtlich / minimal bleiben soll.

**Comment by Nos-** [comment]
Hey,
ich hatte mir überlegt ein möglichst universelles aber dennoch einheitliches Datenformat zu verwenden (das natürlich ein offener Standard sein sollte!). Newsfeeds auf der offiziellen Homepage scheinen mir da eine gute Lösung zu sein. Natürlich könnte man auch Mikroformate, Kalendereinträge etc.  abgrasen, wenn man Zeit und Nerven dafür hat.

Für die Darstellung in der App wäre es natürlich gut, wenn es einen eigenen Bereich/ Seite gäbe, auf dem das wichtigste sowie aktuelle Neuigkeiten stehen. Als Ausbaustufe wäre eine Filterfunktion für, in den einzelnen Feeds enthaltene, Kategorien/Tags praktisch. Die aktuellsten News könnte man ja auch noch an zentralerer Stelle darstellen.
Bei der heutigen FSR-Sitzung habe ich die App auch kurz angesprochen. Es wird möglicherweise darauf hinaus laufen, das jeder FSR einen eigenen Newsfeed auf seiner Homepage verlinkt und befüttert. Diese brauchen dann nur noch abgegriffen und weiterverwendet zu werden. (Möglicherweise macht das dann sogar der StuRa selbst. Eine einfache Filterfunktion nach Tags wäre dann natürlich nicht schlecht.)

**Comment by FestPlatin** [comment]
Hey,
die Erstellung und Bereitstellung einer API zur Abfrage der Daten würde ich in die Hände des StuRa legen. Eure Systeme und Daten kennt ihr ja am besten und könnt darauf ja auch eine entsprechende Schnittstelle entwickeln. Für die App würde auch vorerst der RSS-Feed ausreichen. Sollte es dann eine performantere Schnittstelle geben würden wir auf diese Ausweichen. Aber extra eine zu entwickeln ist nicht notwendig und auch nicht unsere Aufgabe.

#### Einbindung
Meiner Meinung nach bringt eine eigene Seite / Bereich nicht viel. Außer StuRa Mitarbeitern kann ich mir nicht vorstellen das dieser von einem Großteil verwendet wird (siehe dazu auch Bibliothek).

Besser finde ich da schon die Idee mit dem FSR-Newsfeed. Sowas könnte man einfach mit auf der Übersichtsseite einbinden. Eine Auswahl welchen und ob man einen erhalten möchte kann man einfach über die Einstellungen regeln. Die Anzeige könnte ich mir ähnlich der von Google-Now vorstellen.

Ich merke auch gerade das sich die StuRa-News auch stark in Grenzen halten (was meinen ersten Punkt unter Einbindung wieder unterstützt). Bei den Terminen sind es dann schon einige mehr. Da müsste man auf jeden Fall etwas filtern.

**Comment by FestPlatin** [comment]
Sollte es hier Neuigkeiten zu einer Stura-API geben, kann das Ticket gerne wieder geöffnet werden. Bis dahin schließe ich es erstmal.
