### ISSUE TITLE
Fehler: Aktualisierung lösch Änderungen am Stundenplan

### ISSUE THREAD

**Issue by s72785** [HTWDD/HTWDresden#10]
Im trivialsten Fall wurden Kurse aus dem Stundenplan entfernt und tauchen bei jeder Aktualisierung (ggf. auch unbeabsichtigt) wieder auf.
Noch schlimmer ist es wenn Hinzutragungen dabei waren, denn die verschwinden.

Votschlag: Plan YY/SSS/AA zusammen mit Informationen zu den Änderungen (+,-) speichern. Dadurch könnten auch mehrere Pläne leichter kombiniert werden.
Ansonsten: Bitte den Nutzer vor unvorhergesehenen Dingen (optional abschaltbar) warnen.

Da aber nur aktuelle und folgende Woche direkt anzeig- und bearbeitbar sind und es keine Sync zu einem Kalender-Service gibt, ist der Plan hier nur bedingt hilfreich. Daher wahrscheinlich zu viel Liebesmüh.

**Comment by FestPlatin** [comment]
_Intern: #2016101073000028_
Als Fehler würde ich es nicht gleich abstempeln, ist eher ein neues Feature :) Aber da dieses Thema immer mal wieder hochkommt, ist es schon geplant daran was zu ändern.
Bis jetzt wurde bereits folgende Möglichkeiten Überlegt:

### Bestätigungsabfrage
Bevor die Daten aktualisiert werden, erscheint eine Hinweismeldung. Wäre die einfachste und schnellste Möglichkeit. Verhindert allerdings nur unbeabsichtigte Aktualisieren. Passt allerdings nicht wirklich in das aktuelle Design-Konzept.

### Update über Knopf
Wie in der alten Version könnte es einen Aktualisieren Knopf geben, dies würde eventuell versehentliches Updaten verhindern. Passt allerdings komplett nicht ins Design.

### Geänderte oder manuelle Einträge werden bei einem Update nicht gelöscht.
Geänderte oder manuelle Einträge werden mit einem Flag markiert und bei einem Update nicht geändert / gelöscht. Wobei ich hier den Fokus eher auf die manuellen Einträge legen würde. Das ist aktuell meine bevorzugte Variante.

### Allgemein
Für das Speichern der Änderungen benötigt man prinzipiell eine eindeutige ID um einen Datensatz wieder zu identifizieren. Diesen gibt es leider einfach technisch nicht. Aus diesem Grund kann auch nicht verhindert werden das bereits gelöschte Einträge wieder erscheinen.


Was stellst du dir direkt mit einem Sync zu einem Kalender-Service vor?

**Comment by s72785** [comment]
> Was stellst du dir direkt mit einem Sync zu einem Kalender-Service vor?

[CalDAV](https://tools.ietf.org/html/rfc4791)

**Comment by FestPlatin** [comment]
Man könnte prinzipiell mit den vorhanden Daten und öffentlichen Feiertagen ein CalDAV-Anbindung nachbauen. Hat aber glaube gerade nicht viel mit dem allgemeinen Update-Problem zu tun.

**Comment by s72785** [comment]
Für Nutzerdefinierte Daten (zur Unterscheidung von den Publik-Daten der HTW) muss der Nutzer natürlich eine Datensenke definieren; das kann auch die Kalender-App auf dem Smartphone/Tablet sein.

**Comment by FestPlatin** [comment]
Umstellung Stundenplan: individuelle Stundenpläne werden jetzt nicht mehr überschrieben.
