### ISSUE TITLE
APK

### ISSUE THREAD

**Issue by a1lu** [HTWDD/HTWDresden#3]
Huhu
kannst du eine APK hochladen damit wir uns die App installieren koennen?

**Comment by FestPlatin** [comment]
Hier der aktuelle Entwicklungsstand:
http://www2.htw-dresden.de/~s71513/HTWDresden/app-release.apk
Ich werde die Datei in unregelmäßigen Abständen mal aktualisieren.

**Comment by FestPlatin** [comment]
Evaluierung der App beendet.
