### ISSUE TITLE
Probleme (Nutzertest)

### ISSUE THREAD

**Issue by a1lu** [HTWDD/HTWDresden#4]
Hallo,
folgende Probleme haben sich beim Nutzertest herausgestellt:

Career-Service: Termin kann in der Vergangenheit liegen
Stundenplan: Name vom Dozent nicht einstellbar, wenn keine Kurzform eingegeben wird steht nix da
Prüfung: IM-Knopf wurde mit Medianinformatik verwechselt, (Vorschlag: ädnerung zu Jahrgang zwecks Einheitlichkeit in der App)
Belegungsplan: Eingabemuster muss genau beachtet werden, ein anstaendiges Parsen waere schoen, Wunsch: Option zum suchen nach einem freien Raum zur einer angegebenen Uhrzeit

Die Startseite wurde von einem als nervig Empfunden und er wuerde gern das Sideboard als startmenue haben

**Comment by FestPlatin** [comment]
Hey,
vielen Dank für eure Anmerkungen. Meine Anmerkung in Bezug auf die neue App:
- Career-Service: Ist in der neuen App vorerst nicht mit enthalten.
- Stundenplan: Das verstehe ich nicht ganz. Aber prinzipiell ist es richtig. Der Prof-Stundenplan ist ausschließlich für die Professoren gedacht. Zur Abfrage besitzen diese eine eigene geheime Kennung. Ich erwähne dies jetzt bei der Eingabe nochmal extra.
- Prüfung: Die Felder habe ich in "Jahrgang" umbenannt.
- Belegungsplan: Steht noch auf der ToDO-Liste

**Comment by a1lu** [comment]
> * Stundenplan: Das verstehe ich nicht ganz. Aber prinzipiell ist es richtig. Der Prof-Stundenplan ist ausschließlich für die Professoren gedacht. Zur Abfrage besitzen diese eine eigene geheime Kennung. Ich erwähne dies jetzt bei der Eingabe nochmal extra.

Wenn man sich selber Stundenanlegt kann man eben keinen Dozenten eintragen. Das kannschon nervig sein.
Der zweite Punkt zum Stundenplan ist eben, dass kein Name der Vorlesung angezeigt wird, wenn keine Kurzform angegeben ist.
