### ISSUE TITLE
Fehler bei Berechnung der Kalenderwoche

### ISSUE THREAD

**Issue by vv01f** [HTWDD/HTWDresden#8]
Die App zeigt für den Stundenplam am 11.10. die 42. KW an. Tatsächlich haben wir aber die 41. KW.

Ich fürchte das kann zu Problemen bei der Pflege des Stundenplanes kommen.

**Comment by FestPlatin** [comment]
Das Problem scheint aktuell nur aufzutreten wenn als Standardsprache nicht Deutsch eingestellt ist. Sobald Deutsch (bzw. auch Englisch (England)) eingestellt ist, wird die richtige Kalenderwoche erkannt. Ein Entsprechender Bugfix ist für die nächste Version geplant.
