### ISSUE TITLE
Wunsch: Anzeige von Stundenplanänderungen im Startbildschirm

### ISSUE THREAD

**Issue by vv01f** [HTWDD/HTWDresden#9]
fromm aber evtl. ja für die Zukunft.

Derzeit z.B.: https://www.htw-dresden.de/wiwi/service/stundenplanaenderungen.html

Sollte maschinenlesbar irgendwo rumliegen, wenn noch nicht wäre es im Interesse der HS da zu ändern.

Mal abgesehen davon, dass die ihre Informationspflicht gerade verletzen.

**Comment by FestPlatin** [comment]
Hallo vv01f,
Stundenplanänderungen wären für die App durchaus sehr interessant, vor allem bei kurzfristigen Änderungen könnten die Studenten entsprechend informiert werden.

Die Fakultät Wirtschaftswissenschaften scheint allerdings aktuell die einzigen zu sein, welche eine solche Übersicht pflegen. Im Stundenplan der Pillnitzer-Außenstelle finden sich ebenfalls Informationen die ausgewertet werden können. Das ganze jetzt maschinenlesbar irgendwie aufzubereiten ist ein immenser Aufwand der sich eigentlich nicht lohnt. Ich bin auch kein Student mehr, daher ist meine Zeit jetzt auch begrenzt irgendwelche Sachen in meiner Freizeit umzusetzen.

Da ja das geplante Campusmanagementsystem, welches solche Informationen bereitstellen sollte, ja noch auf sich warten lässt, werden wir die nächste Zeit wirklich nicht darum kommen uns eigene Schnittstellen zu definieren. Nur wenn wir dies machen, sollten wir es auch richtig angehen und nicht jede einzelne Seite parsen. Ich würde es daher bevorzugen wenn ein Modulares System geschaffen würde in welches die Informationen valide eingegeben werden können und anschließend über definierte Schnittstellen abgefragt werden können. Sowas könnte man doch auch wunderbar als Projektarbeit in verschiedenen Lehrveranstaltungen anbieten. Da würde ich zur Unterstützung auch etwas Zeit investieren und du würdest deine Schnittstelle bekommen ;)

**Comment by vv01f** [comment]
Danke schonmal; ich habe natürlich die Illusion gehabt, dass die Hochschule ein Interesse daran hätte…

Leider ist es eher so, dass die Fakultäten für "ihre" Lehre verantwortlich sind. Und im Zweifel wollen Sie das auch nicht sein, sondern schieben das auf die Professoren ab.

Ein Entwurf für eine Bitte an die WiWis liegt bei StuRa/HoPo, die Administration nimmt ja Anregungen von Studenten eher nicht an. Mal sehen in welchem Jahrzehnt soetwas ankommt. 

Falls jemand mit einem Prof z.B. eine Projekt-/Abschlussarbeit verabredet bekommt sehe ich da mehr Chancen als auf dem Wege über die Verwaltung/Kanzlerin/(Pro-)Rektor.

**Comment by FestPlatin** [comment]
Ich lebe aber glaube auch in einer Illusion. Ich sehe in der Aufgabe eine so schön umfassende Projektaufgabe welche Lehrinhalte aus verschiedenen Semestern und Fächern miteinander verknüpft. Gerade meinen Studiengang hätte etwas praktische Projektarbeit nicht geschadet (In anderen Studiengängen ist dies übrigens vollkommen anders).
Wenn man weiß mit welchen Mitteln an manchen Stellen Inhalte erstellt / gepflegt werden ist es umso trauriger warum man nicht fakultätsübergreifend Aufgaben vergibt.

**Comment by FestPlatin** [comment]
Da sich hier scheinbar nichts neues von der Hochschule gibt, wird das Ticket erstmal geschlossen. Sollte eine solche API später verfügbar sein, wäre eine Einbau in die App natürlich interessant.
